// =============================================================================
// Qasm: compiles circuits to OpenQASM 3
//
// The same words as quantum.rl, but instead of simulating, every circuit
// writes an OpenQASM 3 program to `name.qasm` in the current directory. Such
// a file can run on an IBM quantum computer through Qiskit.
//
// Choosing a backend means choosing a library:
//   include "quantum.rl"   the circuit is simulated
//   include "qasm.rl"      the circuit compiles to OpenQASM 3
//
// Differences from the simulator:
// - `prepare q random` draws the angles at compile time and writes them out.
// - `expect q == ref` undoes ref's preparation on q and measures q into the
//   bit expect_q. On ideal hardware this bit is always 0.
// - `barrier a, b` stops the Qiskit compiler from simplifying the circuit
//   across this point. Without it, a circuit with a known outcome, such as
//   superdense coding, would be reduced to bare X gates and measurements.
// - `when bit { ... }` becomes an `if` evaluated on the quantum computer
//   mid-circuit.
// - `probability`, `fidelity` and `check` do not exist, because the quantum
//   state cannot be read out on hardware. `show` and `say` become comments.
// =============================================================================

link shared "c"
link shared "m"
extern malloc(size:u64) -> u8* abi sysv-amd64
extern free(pointer:u8*) -> void abi sysv-amd64
extern strdup(text:u8*) -> u8* abi sysv-amd64
extern printf(format:u8*, ...) -> i64 abi sysv-amd64
extern fprintf(stream:u8*, format:u8*, ...) -> i64 abi sysv-amd64
extern fopen(path:u8*, mode:u8*) -> u8* abi sysv-amd64
extern fclose(stream:u8*) -> i64 abi sysv-amd64
extern snprintf(out:u8*, size:u64, format:u8*, ...) -> i64 abi sysv-amd64
extern time(out:u8*) -> i64 abi sysv-amd64
extern srand48(seed:i64) -> void abi sysv-amd64
extern drand48() -> f64 abi sysv-amd64
extern acos(value:f64) -> f64 abi sysv-amd64

let Qasm = phrase { dictionary = true }

record Qasm:Reg {
    n:i64
    names:u8**
    theta:f64*
    phi:f64*
    indent:i64
    out:u8*
    indices:i64*
    sizes:i64*
}

let Qasm:new = fn (name:u8*) -> i64 {
    var r:Qasm:Reg* = cast(Qasm:Reg*, malloc(64))
    r.n = 0
    r.names = cast(u8**, malloc(8 * 64))
    r.theta = cast(f64*, malloc(8 * 64))
    r.phi = cast(f64*, malloc(8 * 64))
    r.indent = 0
    r.indices = cast(i64*, malloc(8 * 64))
    r.sizes = cast(i64*, malloc(8 * 64))
    var k = 0
    while k < 64 {
        r.indices[k] = k
        r.sizes[k] = 1
        k += 1
    }
    var path:u8* = malloc(512)
    snprintf(path, 512, "%s.qasm", name)
    r.out = fopen(path, "w")
    if !r.out {
        printf("qasm: cannot open file %s\n", path)
        free(path)
        return 0
    }
    printf("qasm: writing %s\n", path)
    free(path)
    fprintf(r.out, "// Circuit %s generated by RecurLoop from the qasm.rl library\nOPENQASM 3.0;\ninclude \"stdgates.inc\";\n\n", name)
    return cast(i64, r)
}

let Qasm:release = fn (h:i64) -> i64 {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    var i = 0
    while i < r.n {
        free(r.names[i])
        i += 1
    }
    fclose(r.out)
    free(cast(u8*, r.names))
    free(cast(u8*, r.theta))
    free(cast(u8*, r.phi))
    free(cast(u8*, r.indices))
    free(cast(u8*, r.sizes))
    free(cast(u8*, r))
    return 0
}

let Qasm:out = fn (h:i64) -> u8* {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    return r.out
}

let Qasm:pad = fn (h:i64) -> i64 {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    var i = 0
    while i < r.indent {
        fprintf(Qasm:out(h), "    ")
        i += 1
    }
    return 0
}

let Qasm:alloc = fn (h:i64, name:u8*) -> i64 {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    r.names[r.n] = strdup(name)
    fprintf(Qasm:out(h), "qubit %s;\n", name)
    r.n = r.n + 1
    return r.n - 1
}

// A register in OpenQASM 3: `qubit[count] name;` with qubits name[0], name[1], ...
// Returns a pointer to an index array, like Quantum:alloc_reg.
let Qasm:alloc_reg = fn (h:i64, name:u8*, count:i64) -> i64* {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    var first = r.n
    fprintf(Qasm:out(h), "qubit[%lld] %s;\n", count, name)
    var label:u8* = malloc(64)
    var k = 0
    while k < count {
        snprintf(label, 64, "%s[%lld]", name, k)
        r.names[r.n] = strdup(label)
        r.n = r.n + 1
        k += 1
    }
    free(label)
    r.sizes[first] = count
    return cast(i64*, cast(i64, r.indices) + 8 * first)
}

let Qasm:nm = fn (h:i64, q:i64) -> u8* {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    return r.names[q]
}

let Qasm:g1 = fn (h:i64, gate:u8*, t:i64) -> i64 {
    Qasm:pad(h)
    fprintf(Qasm:out(h), "%s %s;\n", gate, Qasm:nm(h, t))
    return 0
}

let Qasm:g1a = fn (h:i64, gate:u8*, angle:f64, t:i64) -> i64 {
    Qasm:pad(h)
    fprintf(Qasm:out(h), "%s(%.17g) %s;\n", gate, angle, Qasm:nm(h, t))
    return 0
}

let Qasm:g2 = fn (h:i64, gate:u8*, a:i64, b:i64) -> i64 {
    Qasm:pad(h)
    fprintf(Qasm:out(h), "%s %s, %s;\n", gate, Qasm:nm(h, a), Qasm:nm(h, b))
    return 0
}

let Qasm:g2a = fn (h:i64, gate:u8*, angle:f64, a:i64, b:i64) -> i64 {
    Qasm:pad(h)
    fprintf(Qasm:out(h), "%s(%.17g) %s, %s;\n", gate, angle, Qasm:nm(h, a), Qasm:nm(h, b))
    return 0
}

let Qasm:g3 = fn (h:i64, gate:u8*, a:i64, b:i64, c:i64) -> i64 {
    Qasm:pad(h)
    fprintf(Qasm:out(h), "%s %s, %s, %s;\n", gate, Qasm:nm(h, a), Qasm:nm(h, b), Qasm:nm(h, c))
    return 0
}

let Qasm:do_measure = fn (h:i64, t:i64, bit:u8*) -> i64 {
    Qasm:pad(h)
    fprintf(Qasm:out(h), "bit[1] %s;\n", bit)
    Qasm:pad(h)
    fprintf(Qasm:out(h), "%s[0] = measure %s;\n", bit, Qasm:nm(h, t))
    return 0
}

// Measures a whole register into a bit variable of the same length.
let Qasm:read_reg = fn (h:i64, r:i64*, bit:u8*) -> i64 {
    var reg:Qasm:Reg* = cast(Qasm:Reg*, h)
    var count = reg.sizes[r[0]]
    Qasm:pad(h)
    fprintf(Qasm:out(h), "bit[%lld] %s;\n", count, bit)
    var k = 0
    while k < count {
        Qasm:pad(h)
        fprintf(Qasm:out(h), "%s[%lld] = measure %s;\n", bit, k, Qasm:nm(h, r[k]))
        k += 1
    }
    return 0
}

// Angles drawn at compile time: the QASM program gets a concrete state.
let Qasm:init_state = fn (h:i64, t:i64, theta:f64, phi:f64) -> i64 {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    r.theta[t] = theta
    r.phi[t] = phi
    Qasm:g1a(h, "ry", theta, t)
    Qasm:g1a(h, "p", phi, t)
    return 0
}

let Qasm:init_random = fn (h:i64, t:i64) -> i64 {
    var theta = acos(1.0 - 2.0 * drand48())
    var phi = 2.0 * 3.14159265358979323846 * drand48()
    return Qasm:init_state(h, t, theta, phi)
}

// expect t == ref on hardware: undo the preparation and measure.
// If t is in ref's state, the measurement always gives 0.
let Qasm:verify = fn (h:i64, t:i64, ref:i64) -> i64 {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    Qasm:pad(h)
    fprintf(Qasm:out(h), "// expect %s == %s: after undoing the preparation the measurement must give 0\n", Qasm:nm(h, t), Qasm:nm(h, ref))
    Qasm:g1a(h, "p", 0.0 - r.phi[ref], t)
    Qasm:g1a(h, "ry", 0.0 - r.theta[ref], t)
    Qasm:pad(h)
    fprintf(Qasm:out(h), "bit[1] expect_%s;\n", Qasm:nm(h, t))
    Qasm:pad(h)
    fprintf(Qasm:out(h), "expect_%s[0] = measure %s;\n", Qasm:nm(h, t), Qasm:nm(h, t))
    return 0
}

let Qasm:open_if = fn (h:i64, bit:u8*) -> i64 {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    Qasm:pad(h)
    fprintf(Qasm:out(h), "if (%s[0]) {\n", bit)
    r.indent = r.indent + 1
    return 0
}

let Qasm:close = fn (h:i64) -> i64 {
    var r:Qasm:Reg* = cast(Qasm:Reg*, h)
    r.indent = r.indent - 1
    Qasm:pad(h)
    fprintf(Qasm:out(h), "}\n")
    return 0
}

let Qasm:comment = fn (h:i64, text:u8*) -> i64 {
    Qasm:pad(h)
    fprintf(Qasm:out(h), "// %s\n", text)
    return 0
}

fn pi() -> f64 {
    return 3.14159265358979323846
}

let qasm_seed = fn (v:i64) -> i64 {
    srand48(v)
    return 0
}

syntax circuit <name:id> <body:block> => fn ${name}() -> i64 {
    var qs = Qasm:new("${name}")
    defer Qasm:release(qs)
    if 1 == 1 ${body}
    return 0
}

syntax extend circuit <name:id> "(" <params:raw> ")" <body:block> => fn ${name}(${params}) -> i64 {
    var qs = Qasm:new("${name}")
    defer Qasm:release(qs)
    if 1 == 1 ${body}
    return 0
}

syntax qubit <name:id> => var ${name} = Qasm:alloc(qs, "${name}")
syntax qubits <name:id> "[" <count:expr> "]" => var ${name}:i64* = Qasm:alloc_reg(qs, "${name}", ${count})
syntax seed <value:expr> => qasm_seed(${value})

syntax H <t:expr> => Qasm:g1(qs, "h", ${t})
syntax X <t:expr> => Qasm:g1(qs, "x", ${t})
syntax Y <t:expr> => Qasm:g1(qs, "y", ${t})
syntax Z <t:expr> => Qasm:g1(qs, "z", ${t})
syntax S <t:expr> => Qasm:g1(qs, "s", ${t})
syntax T <t:expr> => Qasm:g1(qs, "t", ${t})
syntax RX "(" <angle:expr> ")" <t:expr> => Qasm:g1a(qs, "rx", ${angle}, ${t})
syntax RY "(" <angle:expr> ")" <t:expr> => Qasm:g1a(qs, "ry", ${angle}, ${t})
syntax RZ "(" <angle:expr> ")" <t:expr> => Qasm:g1a(qs, "rz", ${angle}, ${t})
syntax P "(" <angle:expr> ")" <t:expr> => Qasm:g1a(qs, "p", ${angle}, ${t})
syntax CNOT <c:expr> "," <t:expr> => Qasm:g2(qs, "cx", ${c}, ${t})
syntax CZ <c:expr> "," <t:expr> => Qasm:g2(qs, "cz", ${c}, ${t})
syntax CP "(" <angle:expr> ")" <c:expr> "," <t:expr> => Qasm:g2a(qs, "cp", ${angle}, ${c}, ${t})
syntax SWAP <a:expr> "," <b:expr> => Qasm:g2(qs, "swap", ${a}, ${b})
syntax TOFFOLI <c1:expr> "," <c2:expr> "," <t:expr> => Qasm:g3(qs, "ccx", ${c1}, ${c2}, ${t})
syntax barrier <a:expr> "," <b:expr> => Qasm:g2(qs, "barrier", ${a}, ${b})

syntax measure <t:id> "->" <name:id> => var ${name} = Qasm:do_measure(qs, ${t}, "${name}")
syntax extend measure all <r:id> "->" <name:id> => var ${name} = Qasm:read_reg(qs, ${r}, "${name}")
syntax reset <t:expr> => Qasm:g1(qs, "reset", ${t})
syntax prepare <t:expr> random => Qasm:init_random(qs, ${t})
syntax extend prepare <t:expr> "(" <theta:expr> "," <phi:expr> ")" => Qasm:init_state(qs, ${t}, ${theta}, ${phi})

// A condition on a measurement result, evaluated on the quantum computer.
syntax when <bit:id> <body:block> => if 1 == 1 {
    Qasm:open_if(qs, "${bit}")
    if 1 == 1 ${body}
    Qasm:close(qs)
}

syntax show "state" => Qasm:comment(qs, "show state")
syntax extend show bloch <t:expr> => Qasm:comment(qs, "show bloch")
syntax say <text:string> => Qasm:comment(qs, ${text})
syntax expect <t:expr> "==" <ref:expr> => Qasm:verify(qs, ${t}, ${ref})

let qasm_clock_seed = fn () -> i64 {
    srand48(time(cast(u8*, 0)))
    return 0
}
qasm_clock_seed()
