// Circuit chsh_01 generated by RecurLoop from the qasm.rl library
OPENQASM 3.0;
include "stdgates.inc";

qubit alice;
qubit bob;
h alice;
cx alice, bob;
barrier alice, bob;
ry(0) alice;
ry(0.78539816339744828) bob;
bit[1] a;
a[0] = measure alice;
bit[1] b;
b[0] = measure bob;
