"""Helpers shared by check_noise.py and run_ibm.py."""

from pathlib import Path

from qiskit import qasm3

DIRECTORY = Path(__file__).resolve().parent
TELEPORTATION = ["teleportation", "teleportation_deferred", "control"]
SUPERDENSE = ["superdense_00", "superdense_01", "superdense_10", "superdense_11"]
CHSH = ["chsh_00", "chsh_01", "chsh_10", "chsh_11"]
QFT = [f"qft_{k}" for k in range(8)]
GROVER = [f"grover2_{k}" for k in range(4)] + [f"grover3_{k}" for k in range(8)]
CIRCUITS = TELEPORTATION + SUPERDENSE + CHSH + QFT + GROVER
SETS = {
    "all": CIRCUITS,
    "teleportation": TELEPORTATION,
    "superdense": SUPERDENSE,
    "chsh": CHSH,
    "qft": QFT,
    "grover": GROVER,
}


def load(name):
    """Loads the file name.qasm generated by generate_qasm.rl."""
    path = DIRECTORY / f"{name}.qasm"
    if not path.exists():
        raise SystemExit(
            f"Missing {path.name}. First run in this directory:\n"
            "  recurloop --file generate_qasm.rl"
        )
    circuit = qasm3.loads(path.read_text())
    circuit.name = name
    return circuit


def register(data, *names):
    """Returns the first classical register of the given names that exists.

    Jobs submitted before the project was translated to English use the
    Polish register names, so readers accept both.
    """
    for name in names:
        if hasattr(data, name):
            return getattr(data, name)
    raise RuntimeError(f"none of the registers {names} is in the result")


def score(name, data, shots):
    """Returns the fraction of successful runs of a circuit."""
    if name.startswith("superdense_"):
        return score_superdense(name, data, shots)
    if name.startswith("chsh_"):
        return score_chsh(name, data, shots)
    if name.startswith("qft_"):
        return score_qft(name, data, shots)
    if name.startswith("grover"):
        return score_grover(name, data, shots)
    return score_expect(name, data, shots)


def score_expect(name, data, shots):
    """Returns the fraction of runs in which the expect bit is 0.

    The expect bit is the measurement after undoing the preparation of psi.
    A successful teleportation always gives 0. A completely random state of
    Bob's would give 0 in only half of the runs.
    """
    registers = [r for r in dir(data) if r.startswith("expect_")]
    if len(registers) != 1:
        raise RuntimeError(f"{name}: expected one expect_ register, got {registers}")
    counts = getattr(data, registers[0]).get_counts()
    return counts.get("0", 0) / shots


def bob_reads(data):
    """Returns the two-bit messages Bob decoded, e.g. "10"."""
    first = register(data, "decoded1", "odczyt1").get_bitstrings()
    second = register(data, "decoded2", "odczyt2").get_bitstrings()
    return [a + b for a, b in zip(first, second)]


def score_superdense(name, data, shots):
    """Returns the fraction of runs in which Bob decoded the message sent.

    The message is in the circuit name: superdense_10 sends the bits 1 and 0.
    Guessing, Bob would hit one of the four messages 25% of the time.
    """
    message = name.removeprefix("superdense_")
    return bob_reads(data).count(message) / shots


def score_chsh(name, data, shots):
    """Returns the fraction of CHSH rounds won.

    The questions are in the circuit name: chsh_10 means x = 1, y = 0. A round
    is won when a XOR b = x AND y.
    """
    x, y = (int(c) for c in name.removeprefix("chsh_"))
    wins = sum(
        (int(a) ^ int(b)) == (x & y)
        for a, b in zip(data.a.get_bitstrings(), data.b.get_bitstrings())
    )
    return wins / shots


def chsh_s(fractions):
    """The CHSH value S from the average win rate of the four circuits.

    For each question pair the correlation is E = 2 * wins - 1, with the
    opposite sign for x = y = 1. S = E00 + E01 + E10 - E11 = 8 * mean_wins - 4.
    Classically S <= 2; quantum mechanics allows S = 2 sqrt(2) = 2.83.
    """
    return 8 * sum(fractions) / len(fractions) - 4


def register_values(data):
    """Returns the numbers read from the result register, bit k is qubit r[k]."""
    return [int(bits, 2) for bits in register(data, "result", "wynik").get_bitstrings()]


def score_qft(name, data, shots):
    """Returns the fraction of runs in which the inverse QFT gave back the number.

    The number is in the circuit name: qft_5 stores 5 in the phases. Guessing
    one of eight numbers would be right 12.5% of the time.
    """
    k = int(name.removeprefix("qft_"))
    return register_values(data).count(k) / shots


def score_grover(name, data, shots):
    """Returns the fraction of runs in which Grover's search found the marked number.

    The register size and the number are in the circuit name: grover3_5 searches
    for 5 among eight numbers. Guessing would be right 25% of the time on two
    qubits and 12.5% on three.
    """
    k = int(name.split("_")[1])
    found = [int(bits, 2) for bits in data.found.get_bitstrings()]
    return found.count(k) / shots
