// Circuit control generated by RecurLoop from the qasm.rl library
OPENQASM 3.0;
include "stdgates.inc";

qubit psi;
ry(1.8586144017765862) psi;
p(2.1128175399482427) psi;
// expect psi == psi: after undoing the preparation the measurement must give 0
p(-2.1128175399482427) psi;
ry(-1.8586144017765862) psi;
bit[1] expect_psi;
expect_psi[0] = measure psi;
