// Circuit grover2_1 generated by RecurLoop from the qasm.rl library
OPENQASM 3.0;
include "stdgates.inc";

qubit[2] r;
h r[0];
h r[1];
x r[1];
cz r[0], r[1];
x r[1];
h r[0];
x r[0];
h r[1];
x r[1];
cz r[0], r[1];
x r[0];
h r[0];
x r[1];
h r[1];
bit[2] found;
found[0] = measure r[0];
found[1] = measure r[1];
