// Circuit qft_1 generated by RecurLoop from the qasm.rl library
OPENQASM 3.0;
include "stdgates.inc";

qubit[3] r;
h r[0];
p(0.78539816339744828) r[0];
h r[1];
p(1.5707963267948966) r[1];
h r[2];
p(3.1415926535897931) r[2];
swap r[0], r[2];
h r[0];
cp(-1.5707963267948966) r[0], r[1];
h r[1];
cp(-0.78539816339744828) r[0], r[2];
cp(-1.5707963267948966) r[1], r[2];
h r[2];
bit[3] result;
result[0] = measure r[0];
result[1] = measure r[1];
result[2] = measure r[2];
