// Circuit superdense_01 generated by RecurLoop from the qasm.rl library
OPENQASM 3.0;
include "stdgates.inc";

qubit alice;
qubit bob;
h alice;
cx alice, bob;
barrier alice, bob;
x alice;
barrier alice, bob;
cx alice, bob;
h alice;
bit[1] decoded1;
decoded1[0] = measure alice;
bit[1] decoded2;
decoded2[0] = measure bob;
