// Circuit teleportation generated by RecurLoop from the qasm.rl library
OPENQASM 3.0;
include "stdgates.inc";

qubit psi;
qubit alice;
qubit bob;
ry(1.4026154045417409) psi;
p(1.5719432478228681) psi;
h alice;
cx alice, bob;
cx psi, alice;
h psi;
bit[1] m1;
m1[0] = measure psi;
bit[1] m2;
m2[0] = measure alice;
if (m2[0]) {
    x bob;
}
if (m1[0]) {
    z bob;
}
// expect bob == psi: after undoing the preparation the measurement must give 0
p(-1.5719432478228681) bob;
ry(-1.4026154045417409) bob;
bit[1] expect_bob;
expect_bob[0] = measure bob;
