// Circuit teleportation_deferred generated by RecurLoop from the qasm.rl library
OPENQASM 3.0;
include "stdgates.inc";

qubit psi;
qubit alice;
qubit bob;
ry(0.89459177757054509) psi;
p(0.098095252614989734) psi;
h alice;
cx alice, bob;
cx psi, alice;
h psi;
cx alice, bob;
cz psi, bob;
// expect bob == psi: after undoing the preparation the measurement must give 0
p(-0.098095252614989734) bob;
ry(-0.89459177757054509) bob;
bit[1] expect_bob;
expect_bob[0] = measure bob;
bit[1] m1;
m1[0] = measure psi;
bit[1] m2;
m2[0] = measure alice;
